version: "3.9"

services:
  web:
    build: .
    command: python client/main.py
    ports:
      - "5000:5000"
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app

  tests:
    build: .
    command: pytest
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app
